# Workflow for buildning and testing .NET projects

name: CI - Unit Test

on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        options: --health-cmd="exit 0" --health-interval=10s --health-timeout=10s --health-retries=3
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: "YourStrong!Passw0rd"
          ACCEPT_EULA: "Y"
          wait-for-service: true

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build ./HealthCareAB.sln --configuration Release --no-restore

      - name: Run unit tests with report
        run: dotnet test ./Tests/UserService.Tests/UserService.Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./Tests/UserService.Tests/TestResults/TestResults.trx
